### ISSUE TITLE
Disable swiping on the tab view

### ISSUE THREAD

**Issue by KhatibFX** [slovnicki/contained_tab_bar_view#24]
Hi, I'm really thankful for your work, I am using it in my app

I wanted to ask about how to disable swiping on the tab view itself to change selected tab. I want to change tabs only by tapping on the tab header. Is there an option for this available, or do I have to modify some code in the library?

Thanks again!

**Comment by slovnicki** [comment]
Great question. Currently, there is no option to do that, but I'm planning to add `TabBarViewProperties` in a similar manner as we have `TabBarProperties`. Then, this behavior will be achievable by setting the `physics` property to `NeverScrollableScrollPhysics()`

I will add that today and update the package on pub.dev to v0.7.0

**Comment by KhatibFX** [comment]
Thanks a lot! I really appreciate the effort!

**Comment by slovnicki** [comment]
Hey, I implemented it and is documented at https://pub.dev/packages/contained_tab_bar_view#tabbarviewproperties
