### ISSUE TITLE
onChange gets called twice 

### ISSUE THREAD

**Issue by Zeynal7** [slovnicki/contained_tab_bar_view#28]
Hi,

There is a problem with onChange being called twice when user clicks on a tab. I know that this is something intended with flutter TabController. But I would like to know, if it is possible to make it so that this function gets called only once. (or adding a bool field to ask a user, if user wants it being called twice or not)

I have found a solution [here](https://stackoverflow.com/questions/60252355/tabcontroller-listener-called-multiple-times-how-does-indexischanging-work): 

Currently in this package onChange is called like this.
`    _controller = TabController(
      length: widget.tabs.length,
      vsync: this,
      initialIndex: widget.initialIndex,
    )..addListener(() => widget.onChange(_controller.index));`

Is it possible to change it to the solution that is mentioned above url?
Like this:
`   _controller = TabController(
      length: widget.tabs.length,
      vsync: this,
      initialIndex: widget.initialIndex,
    )..addListener(() {
        if(!_controller.indexIsChanging) {
          widget.onChange(_controller.index);
        }
      });`

I have changed it in my project. But `pub get` changes it back.

**Comment by slovnicki** [comment]
Thank you for this contribution. 

I like the idea of it still being optional to call twice as is, but the default to be calling just once with the solution you provided.

I will implement it today, update on pub and let you know here by closing this issue when I'm done.

**Comment by slovnicki** [comment]
@Zeynal7 If you'd like to contribute your above solution, feel free to open a Pull Request and I will merge you code.

Then later I'll just add some optional attribute on `ContainedTabBarView` with which one can call twice if desired.

**Comment by Zeynal7** [comment]
@slovnicki I think I created Pull request. I am not sure if I did it correctly as it was first time for me. 

Thanks.

**Comment by slovnicki** [comment]
You made it correctly. Thanks
