### ISSUE TITLE
Migrate to null-safety 

### ISSUE THREAD

**Issue by Shadow60539** [slovnicki/contained_tab_bar_view#30]

**Comment by slovnicki** [comment]
@Shadow60539 Indeed, that should be done soon.
First, the `container_tab_indicator` package needs to be migrated, which has already been done by @devj3ns, but I haven't merged it yet: https://github.com/slovnicki/container_tab_indicator/pull/11

**Comment by devj3ns** [comment]
Hey @Shadow60539 👋

The [container_tab_indicator](https://pub.dev/packages/container_tab_indicator) package is now migrated to null safety. 😄

I am currently working on migrating this package. The null safe version will drop in the next few days.

**Comment by devj3ns** [comment]
The master is now migrated to null safety (https://github.com/slovnicki/contained_tab_bar_view/commit/49cfaeebb14c16f787fecead44f0ad88ca1fdc98) 😀

@Shadow60539, could you please import `contained_tab_bar_view` via git and test is everything in your project works? 

If that is the case and @slovnicki is okay with all the changes I made, I will publish v0.8.0 to pub.dev 😄

**Comment by Shadow60539** [comment]
✔ @devj3ns works flawlessly now
